apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ubuntu-app
  labels:
    app: my-ubuntu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu-app
  template:
    metadata:
      labels:
        app: my-ubuntu-app
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:25.04 # <--- IMPORTANT: Your image here
        ports:
        - containerPort: 80